---
#===========[Краткое описание и инструкция]================================================
# Плагин wKillRead версии 1.0.3, сделал [S]vyt - Святослав Дубровский, совместно с (vk.com/plugin_pe и infomcpe.ru)
# Частицы это красивые эффекты вокруг игрока, (true - включить/false - отключить)
# Продолжительность эффектов:1 минута это - 1200 \ 1 Секунда это - 20
# Permissions:
# wkillread.x3 [x3 money] ||| wkillread.x2 [x2 money] ||| wkillread.x3 [x3 money]
#==========================================================================================
ID-effect: 21
Duration: 1200
Amplifier: 0
Particles: true
GiveMoney: 50
Teg-x2: §eVIP
Teg-x3: §eVIP+
BroadCast: 1
tegkill: §f[§6Убийство§f]
#=============[Описание]===================================================================
#ID-Эффекта: Число <- ID Эффекта
#Продолжительность эффекта: Число <- Длительность
#Сила-эффекта: Число <- Сила(Работает не на всех эффектах)
#Частицы: true/false <- Частицы
#Выдача-денег: Число <- Выдача денег | Для групп идет умножение- x2=Число*2 | x3=Число*3
#Тэг-x2: Название <- Текст привелегии убийцы при x2 (Можно использовать цвета §)
#Тэг-x3: Название <- Текст привелегии убийцы при x3 (Можно использовать цвета §)
#                       wKillRead by [S]vyt - vk.com/plugin_pe
#==========================================================================================
...
